### ISSUE TITLE
Password is not being set

### ISSUE THREAD

**Issue by ShintoTuna** [yeetzone/docker-dontstarvetogether#152]
Hello!

When passing PASSWORD ENV variable, for some reason it is not being set. Is there some sort of validation of this string? Maybe it should follow some sort of format? Same thing with WHITELIST. So it seems there is no way for me to restrict random players from accessing my server.

**Comment by thasmo** [comment]
@ShintoTuna, did you figure this out? I've tested this locally and for me this works as intended. Have a look at the [`basic`](https://github.com/yeetzone/docker-dontstarvetogether/tree/master/docs/recipes/basic) server recipe and be sure to set the `TOKEN` and `PASSWORD` in any `.env` file and then start the server. Please feel free to reopen the issue if things don't work out. Thanks! :)
