### ISSUE TITLE
Issues with loading mods via .env file

### ISSUE THREAD

**Issue by dsoyolo** [yeetzone/docker-dontstarvetogether#153]
Hello!

When I add the following to my .env file:
`MODS=2547661042,758532836
#MODS_CONFIGURATION=return { ["workshop-2547661042"]={ configuration_options={  }, enabled=true }, ["workshop-758532836"]={ configuration_options={  }, enabled=true } }`

I browse the running container and see that **/opt/storage/cluster/shard/modoverrides.lua** is populated correctly. Yet, the mods are not enabled when I join the server.

Am I missing something?

**Comment by jwhx** [comment]
I ran into the same problem.
But the server successfully loaded mods, as I use this docker-compose.yml [https://github.com/yeetzone/docker-dontstarvetogether/tree/master/docs/recipes/mods](https://github.com/yeetzone/docker-dontstarvetogether/tree/master/docs/recipes/mods)

**Comment by thasmo** [comment]
@dsoyolo, did you figure it out in the end? I've tested this locally now and the mods I configured were running without problems. If you still have problems please feel free to respond and reopen the issue. Thank you!

**Comment by dsoyolo** [comment]
Hey, thanks for replying. I gave up when I had other issues such as the base data image not being updated to the latest release of the game.

**Comment by thasmo** [comment]
> Hey, thanks for replying. I gave up when I had other issues such as the base data image not being updated to the latest release of the game.

I see, I'm sorry about that. FYI, the automated release pipeline for the data image `yeetzone/dontstarvetogether-data` was broken and therefore the image wasn't updated on Docker Hub. I fixed this some days ago, after I've realized it was broken.
